//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIOT.Resources.Translations
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppTranslations
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppTranslations()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SIOT.Resources.Translations.AppTranslations", typeof(AppTranslations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add card.
        /// </summary>
        internal static string ButtonAddCard
        {
            get
            {
                return ResourceManager.GetString("ButtonAddCard", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ALREADY A USER? LOGIN NOW.
        /// </summary>
        internal static string ButtonAlreadyRegistered
        {
            get
            {
                return ResourceManager.GetString("ButtonAlreadyRegistered", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        internal static string ButtonChange
        {
            get
            {
                return ResourceManager.GetString("ButtonChange", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string ButtonClose
        {
            get
            {
                return ResourceManager.GetString("ButtonClose", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string ButtonConfirm
        {
            get
            {
                return ResourceManager.GetString("ButtonConfirm", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CONTACT US.
        /// </summary>
        internal static string ButtonContactUs
        {
            get
            {
                return ResourceManager.GetString("ButtonContactUs", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string ButtonContinue
        {
            get
            {
                return ResourceManager.GetString("ButtonContinue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dark Theme.
        /// </summary>
        internal static string ButtonDarkTheme
        {
            get
            {
                return ResourceManager.GetString("ButtonDarkTheme", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Download E-Receipt.
        /// </summary>
        internal static string ButtonDownloadReceipt
        {
            get
            {
                return ResourceManager.GetString("ButtonDownloadReceipt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string ButtonEdit
        {
            get
            {
                return ResourceManager.GetString("ButtonEdit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Edit Profile.
        /// </summary>
        internal static string ButtonEditProfile
        {
            get
            {
                return ResourceManager.GetString("ButtonEditProfile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to FACEBOOK.
        /// </summary>
        internal static string ButtonFacebook
        {
            get
            {
                return ResourceManager.GetString("ButtonFacebook", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to FINISH.
        /// </summary>
        internal static string ButtonFinish
        {
            get
            {
                return ResourceManager.GetString("ButtonFinish", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Follow.
        /// </summary>
        internal static string ButtonFollow
        {
            get
            {
                return ResourceManager.GetString("ButtonFollow", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to GOOGLE.
        /// </summary>
        internal static string ButtonGoogle
        {
            get
            {
                return ResourceManager.GetString("ButtonGoogle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Light Theme.
        /// </summary>
        internal static string ButtonLightTheme
        {
            get
            {
                return ResourceManager.GetString("ButtonLightTheme", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to LOGIN.
        /// </summary>
        internal static string ButtonLogin
        {
            get
            {
                return ResourceManager.GetString("ButtonLogin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to NEXT.
        /// </summary>
        internal static string ButtonNext
        {
            get
            {
                return ResourceManager.GetString("ButtonNext", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ButtonOk
        {
            get
            {
                return ResourceManager.GetString("ButtonOk", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string ButtonSave
        {
            get
            {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to See More.
        /// </summary>
        internal static string ButtonSeeMore
        {
            get
            {
                return ResourceManager.GetString("ButtonSeeMore", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string ButtonSend
        {
            get
            {
                return ResourceManager.GetString("ButtonSend", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SIGN IN.
        /// </summary>
        internal static string ButtonSignin
        {
            get
            {
                return ResourceManager.GetString("ButtonSignin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SIGN UP.
        /// </summary>
        internal static string ButtonSignup
        {
            get
            {
                return ResourceManager.GetString("ButtonSignup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SKIP.
        /// </summary>
        internal static string ButtonSkip
        {
            get
            {
                return ResourceManager.GetString("ButtonSkip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SUBMIT.
        /// </summary>
        internal static string ButtonSubmit
        {
            get
            {
                return ResourceManager.GetString("ButtonSubmit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to EXPLORE NOW.
        /// </summary>
        internal static string ButtonTakeTour
        {
            get
            {
                return ResourceManager.GetString("ButtonTakeTour", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to TWITTER.
        /// </summary>
        internal static string ButtonTwitter
        {
            get
            {
                return ResourceManager.GetString("ButtonTwitter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to View All.
        /// </summary>
        internal static string ButtonViewAll
        {
            get
            {
                return ResourceManager.GetString("ButtonViewAll", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to View E-Receipt.
        /// </summary>
        internal static string ButtonViewReceipt
        {
            get
            {
                return ResourceManager.GetString("ButtonViewReceipt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string PageTitleAccount
        {
            get
            {
                return ResourceManager.GetString("PageTitleAccount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to All Services.
        /// </summary>
        internal static string PageTitleAllServices
        {
            get
            {
                return ResourceManager.GetString("PageTitleAllServices", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Bill Payment.
        /// </summary>
        internal static string PageTitleBillPayment
        {
            get
            {
                return ResourceManager.GetString("PageTitleBillPayment", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Confirm Payment.
        /// </summary>
        internal static string PageTitleConfirmPayment
        {
            get
            {
                return ResourceManager.GetString("PageTitleConfirmPayment", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to E-Receipt.
        /// </summary>
        internal static string PageTitleEReceipt
        {
            get
            {
                return ResourceManager.GetString("PageTitleEReceipt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Icons.
        /// </summary>
        internal static string PageTitleFontIcon
        {
            get
            {
                return ResourceManager.GetString("PageTitleFontIcon", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Font Icons.
        /// </summary>
        internal static string PageTitleFontIconFont
        {
            get
            {
                return ResourceManager.GetString("PageTitleFontIconFont", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Mobile Topup.
        /// </summary>
        internal static string PageTitleMobileTopup
        {
            get
            {
                return ResourceManager.GetString("PageTitleMobileTopup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to My Card.
        /// </summary>
        internal static string PageTitleMyCard
        {
            get
            {
                return ResourceManager.GetString("PageTitleMyCard", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Payment Confirm.
        /// </summary>
        internal static string PageTitlePaymentConfirm
        {
            get
            {
                return ResourceManager.GetString("PageTitlePaymentConfirm", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Request Payment.
        /// </summary>
        internal static string PageTitleRequestPayment
        {
            get
            {
                return ResourceManager.GetString("PageTitleRequestPayment", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to QR Services.
        /// </summary>
        internal static string PageTitleScanPay
        {
            get
            {
                return ResourceManager.GetString("PageTitleScanPay", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        internal static string PageTitleStatistics
        {
            get
            {
                return ResourceManager.GetString("PageTitleStatistics", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Transfer Money.
        /// </summary>
        internal static string PageTitleTransferMoney
        {
            get
            {
                return ResourceManager.GetString("PageTitleTransferMoney", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        internal static string StringAboutUs
        {
            get
            {
                return ResourceManager.GetString("StringAboutUs", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Account Options.
        /// </summary>
        internal static string StringAccountOption
        {
            get
            {
                return ResourceManager.GetString("StringAccountOption", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add New Card.
        /// </summary>
        internal static string StringAddNewCard
        {
            get
            {
                return ResourceManager.GetString("StringAddNewCard", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string StringAddress
        {
            get
            {
                return ResourceManager.GetString("StringAddress", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to All Contacts.
        /// </summary>
        internal static string StringAllContact
        {
            get
            {
                return ResourceManager.GetString("StringAllContact", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Already have an account?.
        /// </summary>
        internal static string StringAlreadyHaveAccount
        {
            get
            {
                return ResourceManager.GetString("StringAlreadyHaveAccount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Already a user? Login Now.
        /// </summary>
        internal static string StringAlreadyRegistered
        {
            get
            {
                return ResourceManager.GetString("StringAlreadyRegistered", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string StringAmount
        {
            get
            {
                return ResourceManager.GetString("StringAmount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to M-Wallet.
        /// </summary>
        internal static string StringAppName
        {
            get
            {
                return ResourceManager.GetString("StringAppName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to App Settings.
        /// </summary>
        internal static string StringAppSettings
        {
            get
            {
                return ResourceManager.GetString("StringAppSettings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Build your finance &amp; banking app in minutes.
        /// </summary>
        internal static string StringAppWelcomeSubtitle
        {
            get
            {
                return ResourceManager.GetString("StringAppWelcomeSubtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Welcome to M-WALLET.
        /// </summary>
        internal static string StringAppWelcomeTitle
        {
            get
            {
                return ResourceManager.GetString("StringAppWelcomeTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        internal static string StringBalance
        {
            get
            {
                return ResourceManager.GetString("StringBalance", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Expire date.
        /// </summary>
        internal static string StringCardExpiry
        {
            get
            {
                return ResourceManager.GetString("StringCardExpiry", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string StringCategory
        {
            get
            {
                return ResourceManager.GetString("StringCategory", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Choose Theme.
        /// </summary>
        internal static string StringChooseTheme
        {
            get
            {
                return ResourceManager.GetString("StringChooseTheme", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Comming soon.
        /// </summary>
        internal static string StringCommingSoon
        {
            get
            {
                return ResourceManager.GetString("StringCommingSoon", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        internal static string StringConfirmPassword
        {
            get
            {
                return ResourceManager.GetString("StringConfirmPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MAUIKIT.
        /// </summary>
        internal static string StringCopyright
        {
            get
            {
                return ResourceManager.GetString("StringCopyright", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Create your new password.
        /// </summary>
        internal static string StringCreateNewPassword
        {
            get
            {
                return ResourceManager.GetString("StringCreateNewPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Create password.
        /// </summary>
        internal static string StringCreatePassword
        {
            get
            {
                return ResourceManager.GetString("StringCreatePassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dark mode.
        /// </summary>
        internal static string StringDarkmode
        {
            get
            {
                return ResourceManager.GetString("StringDarkmode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string StringDate
        {
            get
            {
                return ResourceManager.GetString("StringDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete Account.
        /// </summary>
        internal static string StringDeleteAccount
        {
            get
            {
                return ResourceManager.GetString("StringDeleteAccount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dont&apos;t have an account?.
        /// </summary>
        internal static string StringDontHaveAccount
        {
            get
            {
                return ResourceManager.GetString("StringDontHaveAccount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t received code?.
        /// </summary>
        internal static string StringDontReceiveCode
        {
            get
            {
                return ResourceManager.GetString("StringDontReceiveCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string StringEmail
        {
            get
            {
                return ResourceManager.GetString("StringEmail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enable Location.
        /// </summary>
        internal static string StringEnableLocation
        {
            get
            {
                return ResourceManager.GetString("StringEnableLocation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter your full name.
        /// </summary>
        internal static string StringEnterFullname
        {
            get
            {
                return ResourceManager.GetString("StringEnterFullname", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Type your message....
        /// </summary>
        internal static string StringEnterMessage
        {
            get
            {
                return ResourceManager.GetString("StringEnterMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter your password.
        /// </summary>
        internal static string StringEnterPassword
        {
            get
            {
                return ResourceManager.GetString("StringEnterPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The confirm code was sent via email.
        /// </summary>
        internal static string StringEnterReceivedCode
        {
            get
            {
                return ResourceManager.GetString("StringEnterReceivedCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter your email or phone number.
        /// </summary>
        internal static string StringEnterUsername
        {
            get
            {
                return ResourceManager.GetString("StringEnterUsername", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter your email.
        /// </summary>
        internal static string StringEnterYourEmail
        {
            get
            {
                return ResourceManager.GetString("StringEnterYourEmail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Facebook.
        /// </summary>
        internal static string StringFacebook
        {
            get
            {
                return ResourceManager.GetString("StringFacebook", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Login with FaceID.
        /// </summary>
        internal static string StringFaceIdLogin
        {
            get
            {
                return ResourceManager.GetString("StringFaceIdLogin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Fonts.
        /// </summary>
        internal static string StringFontsCount
        {
            get
            {
                return ResourceManager.GetString("StringFontsCount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        internal static string StringForgotPassword
        {
            get
            {
                return ResourceManager.GetString("StringForgotPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        internal static string StringFullname
        {
            get
            {
                return ResourceManager.GetString("StringFullname", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Google.
        /// </summary>
        internal static string StringGoogle
        {
            get
            {
                return ResourceManager.GetString("StringGoogle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolot sit amet.
        /// </summary>
        internal static string StringGridItemTappedMessage
        {
            get
            {
                return ResourceManager.GetString("StringGridItemTappedMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string StringHome
        {
            get
            {
                return ResourceManager.GetString("StringHome", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        internal static string StringHours
        {
            get
            {
                return ResourceManager.GetString("StringHours", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to icons.
        /// </summary>
        internal static string StringIconsCount
        {
            get
            {
                return ResourceManager.GetString("StringIconsCount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Address  line 1.
        /// </summary>
        internal static string StringInputAddress1
        {
            get
            {
                return ResourceManager.GetString("StringInputAddress1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Address line 2.
        /// </summary>
        internal static string StringInputAddress2
        {
            get
            {
                return ResourceManager.GetString("StringInputAddress2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CVV.
        /// </summary>
        internal static string StringInputCardCvv
        {
            get
            {
                return ResourceManager.GetString("StringInputCardCvv", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Card holder name.
        /// </summary>
        internal static string StringInputCardHolder
        {
            get
            {
                return ResourceManager.GetString("StringInputCardHolder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Card Number.
        /// </summary>
        internal static string StringInputCardNumber
        {
            get
            {
                return ResourceManager.GetString("StringInputCardNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string StringInputCity
        {
            get
            {
                return ResourceManager.GetString("StringInputCity", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string StringInputCountry
        {
            get
            {
                return ResourceManager.GetString("StringInputCountry", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string StringInputDescription
        {
            get
            {
                return ResourceManager.GetString("StringInputDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string StringInputFirstName
        {
            get
            {
                return ResourceManager.GetString("StringInputFirstName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        internal static string StringInputLastName
        {
            get
            {
                return ResourceManager.GetString("StringInputLastName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        internal static string StringInputPhoneNumber
        {
            get
            {
                return ResourceManager.GetString("StringInputPhoneNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string StringInputState
        {
            get
            {
                return ResourceManager.GetString("StringInputState", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ZIP code.
        /// </summary>
        internal static string StringInputZip
        {
            get
            {
                return ResourceManager.GetString("StringInputZip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Is RTL.
        /// </summary>
        internal static string StringIsRTL
        {
            get
            {
                return ResourceManager.GetString("StringIsRTL", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Login or register using your email and password.
        /// </summary>
        internal static string StringLoginOrRegister
        {
            get
            {
                return ResourceManager.GetString("StringLoginOrRegister", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to OR LOGIN WITH.
        /// </summary>
        internal static string StringLoginWith
        {
            get
            {
                return ResourceManager.GetString("StringLoginWith", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string StringLogOut
        {
            get
            {
                return ResourceManager.GetString("StringLogOut", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Comming soon....
        /// </summary>
        internal static string StringMessageFeatureCommingSoon
        {
            get
            {
                return ResourceManager.GetString("StringMessageFeatureCommingSoon", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        internal static string StringMobile
        {
            get
            {
                return ResourceManager.GetString("StringMobile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string StringName
        {
            get
            {
                return ResourceManager.GetString("StringName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        internal static string StringNewPassword
        {
            get
            {
                return ResourceManager.GetString("StringNewPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string StringNote
        {
            get
            {
                return ResourceManager.GetString("StringNote", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to or continue with.
        /// </summary>
        internal static string StringOr
        {
            get
            {
                return ResourceManager.GetString("StringOr", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter your password.
        /// </summary>
        internal static string StringPassword
        {
            get
            {
                return ResourceManager.GetString("StringPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        internal static string StringPhoneNumber
        {
            get
            {
                return ResourceManager.GetString("StringPhoneNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter phone number.
        /// </summary>
        internal static string StringPhoneNumberInput
        {
            get
            {
                return ResourceManager.GetString("StringPhoneNumberInput", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pick Color.
        /// </summary>
        internal static string StringPickColor
        {
            get
            {
                return ResourceManager.GetString("StringPickColor", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        internal static string StringPrivacyPolicy
        {
            get
            {
                return ResourceManager.GetString("StringPrivacyPolicy", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Scan QR code to pay, transfer or withdraw.
        /// </summary>
        internal static string StringQrScannerHeader
        {
            get
            {
                return ResourceManager.GetString("StringQrScannerHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Recent Transactions.
        /// </summary>
        internal static string StringRecentTransaction
        {
            get
            {
                return ResourceManager.GetString("StringRecentTransaction", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolot sit amet.
        /// </summary>
        internal static string StringRegisterAnAccount
        {
            get
            {
                return ResourceManager.GetString("StringRegisterAnAccount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Register now.
        /// </summary>
        internal static string StringRegisterNow
        {
            get
            {
                return ResourceManager.GetString("StringRegisterNow", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolot sit amet.
        /// </summary>
        internal static string StringRegisterNowSubtitle
        {
            get
            {
                return ResourceManager.GetString("StringRegisterNowSubtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        internal static string StringRememberLogin
        {
            get
            {
                return ResourceManager.GetString("StringRememberLogin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Resend.
        /// </summary>
        internal static string StringResend
        {
            get
            {
                return ResourceManager.GetString("StringResend", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        internal static string StringSchedule
        {
            get
            {
                return ResourceManager.GetString("StringSchedule", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search here....
        /// </summary>
        internal static string StringSearch
        {
            get
            {
                return ResourceManager.GetString("StringSearch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search name or number.
        /// </summary>
        internal static string StringSearchContact
        {
            get
            {
                return ResourceManager.GetString("StringSearchContact", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search icon.
        /// </summary>
        internal static string StringSearchIcon
        {
            get
            {
                return ResourceManager.GetString("StringSearchIcon", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select Category.
        /// </summary>
        internal static string StringSelectCategory
        {
            get
            {
                return ResourceManager.GetString("StringSelectCategory", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select time.
        /// </summary>
        internal static string StringSelectTime
        {
            get
            {
                return ResourceManager.GetString("StringSelectTime", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Set as default.
        /// </summary>
        internal static string StringSetDefaultCard
        {
            get
            {
                return ResourceManager.GetString("StringSetDefaultCard", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        internal static string StringShare
        {
            get
            {
                return ResourceManager.GetString("StringShare", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string StringSignin
        {
            get
            {
                return ResourceManager.GetString("StringSignin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string StringSignup
        {
            get
            {
                return ResourceManager.GetString("StringSignup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SMS.
        /// </summary>
        internal static string StringSMS
        {
            get
            {
                return ResourceManager.GetString("StringSMS", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string StringStatus
        {
            get
            {
                return ResourceManager.GetString("StringStatus", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Support Center.
        /// </summary>
        internal static string StringSupportCenter
        {
            get
            {
                return ResourceManager.GetString("StringSupportCenter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string StringTime
        {
            get
            {
                return ResourceManager.GetString("StringTime", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Transaction ID.
        /// </summary>
        internal static string StringTransactionID
        {
            get
            {
                return ResourceManager.GetString("StringTransactionID", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Transactions.
        /// </summary>
        internal static string StringTransactions
        {
            get
            {
                return ResourceManager.GetString("StringTransactions", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Transaction Time.
        /// </summary>
        internal static string StringTransactionTime
        {
            get
            {
                return ResourceManager.GetString("StringTransactionTime", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Transfer Amount.
        /// </summary>
        internal static string StringTransferAmount
        {
            get
            {
                return ResourceManager.GetString("StringTransferAmount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Transfer to.
        /// </summary>
        internal static string StringTransferTo
        {
            get
            {
                return ResourceManager.GetString("StringTransferTo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Type your email to receive verification code..
        /// </summary>
        internal static string StringTypeEmailReceiveCode
        {
            get
            {
                return ResourceManager.GetString("StringTypeEmailReceiveCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Update Profile.
        /// </summary>
        internal static string StringUpdateProfile
        {
            get
            {
                return ResourceManager.GetString("StringUpdateProfile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Email or phone number.
        /// </summary>
        internal static string StringUsername
        {
            get
            {
                return ResourceManager.GetString("StringUsername", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Use your credentials to login..
        /// </summary>
        internal static string StringUseYourCredentials
        {
            get
            {
                return ResourceManager.GetString("StringUseYourCredentials", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Verify Code.
        /// </summary>
        internal static string StringVerifyCode
        {
            get
            {
                return ResourceManager.GetString("StringVerifyCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to View All.
        /// </summary>
        internal static string StringViewAll
        {
            get
            {
                return ResourceManager.GetString("StringViewAll", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolot sit amet, 
        ///consectetur adipiscing elit..
        /// </summary>
        internal static string StringWalkthroughSubtitleStep1
        {
            get
            {
                return ResourceManager.GetString("StringWalkthroughSubtitleStep1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolot sit amet, 
        ///consectetur adipiscing elit..
        /// </summary>
        internal static string StringWalkthroughSubtitleStep2
        {
            get
            {
                return ResourceManager.GetString("StringWalkthroughSubtitleStep2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolot sit amet, 
        ///consectetur adipiscing elit..
        /// </summary>
        internal static string StringWalkthroughSubtitleStep3
        {
            get
            {
                return ResourceManager.GetString("StringWalkthroughSubtitleStep3", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The best app for
        ///finance, banking &amp;
        ///e-wallet today.
        /// </summary>
        internal static string StringWalkthroughTitleStep1
        {
            get
            {
                return ResourceManager.GetString("StringWalkthroughTitleStep1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Manage finances
        ///easily with safe
        ///&amp; secure payments.
        /// </summary>
        internal static string StringWalkthroughTitleStep2
        {
            get
            {
                return ResourceManager.GetString("StringWalkthroughTitleStep2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Have an amazing 
        ///experience with
        ///M-Wallet right now!.
        /// </summary>
        internal static string StringWalkthroughTitleStep3
        {
            get
            {
                return ResourceManager.GetString("StringWalkthroughTitleStep3", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Welcome to M-WALLET.
        /// </summary>
        internal static string StringWelcomeToMauiKit
        {
            get
            {
                return ResourceManager.GetString("StringWelcomeToMauiKit", resourceCulture);
            }
        }
    }
}
